apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ include "gorse.proxy.fullname" $ }}
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: proxy
    {{- if $.Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if not $.Values.proxy.autoscaling.enabled }}
  replicas: {{ $.Values.proxy.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" $ | nindent 6 }}
      app.kubernetes.io/component: worker
  {{- if $.Values.proxy.updateStrategy }}
  {{- if (eq $.Values.proxy.kind "Deployment") }}
  strategy: {{- toYaml $.Values.proxy.updateStrategy | nindent 4 }}
  {{- else }}
  updateStrategy: {{- toYaml $.Values.proxy.updateStrategy | nindent 4 }}
  {{- end }}
  {{- end }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" $ | nindent 8 }}
        app.kubernetes.io/component: worker
        {{- if $.Values.proxy.podLabels }}
        {{- include "common.tplvalues.render" ( dict "value" $.Values.proxy.podLabels "context" $ ) | nindent 8 }}
        {{- end }}
      annotations:
        {{- if $.Values.proxy.podAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" $.Values.proxy.podAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      {{- if $.Values.proxy.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" $.Values.proxy.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if $.Values.proxy.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" $.Values.proxy.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" $.Values.proxy.podAffinityPreset "component" "worker" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" $.Values.proxy.podAntiAffinityPreset "component" "worker" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" $.Values.proxy.nodeAffinityPreset.type "key" $.Values.proxy.nodeAffinityPreset.key "values" $.Values.proxy.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if $.Values.proxy.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" $.Values.proxy.tolerations "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $.Chart.Name }}-worker
          image: "{{ $.Values.proxy.image.repository }}:{{ $.Values.proxy.image.tag }}"
          imagePullPolicy: {{ $.Values.proxy.image.pullPolicy }}
          command: 
              - "/usr/bin/gorse-proxy"
              - "--endpoints"
              - {{ include "gorse.proxy.endpoints" $ }}
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          # TODO - We dont have a proper endpoint for health check
          # livenessProbe:
          #   httpGet:
          #     path: /metrics
          #     port: http
          #   initialDelaySeconds: 120
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 0            
          {{- if $.Values.proxy.resources }}
          resources: {{- toYaml $.Values.proxy.resources | nindent 12 }}
          {{- end }}
