{{- if .Values.standalone }}
{{- if and (eq .Values.architecture "standalone") .Values.standalone.persistence.enabled (not .Values.standalone.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gorse.standalone.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: standalone
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.standalone.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.standalone.persistence.size | quote }}
  {{- if .Values.standalone.persistence.storageClass }}
  storageClassName: {{ .Values.standalone.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
{{- end }}
