apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.secretAnnotations .Values.commonAnnotations }}
  annotations:
      {{- if .Values.secretAnnotations }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.secretAnnotations "context" $ ) | nindent 4 }}
      {{- end }}
      {{- if .Values.commonAnnotations }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
      {{- end }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.gorse.auth.dashboard.enabled }}
  auth-username: {{ include "gorse.auth.username" . | b64enc | quote }}
  auth-password: {{ include "gorse.auth.password" . | b64enc | quote }}
  {{- end }}
  {{- if .Values.gorse.auth.api.enabled }}
  api-key: {{ include "gorse.auth.api" . | b64enc | quote }}
  {{- end }}
  cache-uri: {{ include "gorse.cache.uri" . | b64enc | quote }}
  database-uri: {{ include "gorse.database.uri" . | b64enc | quote }}
