name: Test Charts

on:
  push:
    branches:    
      - main
  pull_request:
    branches:    
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0

      - name: Run chart-testing (install)
        run: ct install --charts charts/gorse
